version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: homework9_db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306