version: '3'
services:

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: elasticsearch:8.8.1
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: curl --fail http://localhost:9200 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  java-service:
    image: nikit0s/projector-hsa-homework5:latest
    ports: 
      - '8080:8080'
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - SPRING_DATA_MONGODB_HOST=mongodb
    depends_on:
      - elasticsearch
      - mongodb
    restart: on-failure

volumes:
  mongo_data: {}