version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: homework10_db
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homework10_db
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432