{
 "title": "InfluxDB 2.x Telegraf Docker Dashboard",
 "description": "Basic docker dashboard for InfluxDB 2.x and telegraf collector.",
 "tags": [
  "docker",
  "influxdb2.0",
  "telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "buckets()" },
   {
    "name": "container",
    "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\n  |> keyValues(keyColumns: [\"container_name\"])\n  |> group()\n  |> keep(columns: [\"container_name\"])\n  |> distinct(column: \"container_name\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Cpus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\n  |> filter(fn: (r) => r[\"_field\"] == \"n_cpus\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Images",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\n  |> filter(fn: (r) => r[\"_field\"] == \"n_images\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\n  |> filter(fn: (r) => r[\"_field\"] == \"n_containers_running\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Paused Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\n  |> filter(fn: (r) => r[\"_field\"] == \"n_containers_paused\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Paused Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\n  |> filter(fn: (r) => r[\"_field\"] == \"n_containers_stopped\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Query operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mongodb\")\n  |> filter(fn: (r) => r[\"_field\"] == \"commands\" or r[\"_field\"] == \"deletes\" or r[\"_field\"] == \"getmores\" or r[\"_field\"] == \"inserts\" or r[\"_field\"] == \"updates\")\n  |> derivative(unit: v.windowPeriod, nonNegative: false)\n  |> yield(name: \"derivative\")\n  "
    }
   ]
  },
  {
   "title": "Commands per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mongodb\")\n  |> filter(fn: (r) => r[\"_field\"] == \"commands_per_sec\")\n  |> derivative(unit: v.windowPeriod, nonNegative: true)\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mongodb\")\n  |> filter(fn: (r) => r[\"_field\"] == \"net_in_bytes\" or r[\"_field\"] == \"net_out_bytes\")\n  |> derivative(unit: v.windowPeriod, nonNegative: true)\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "Document operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mongodb\")\n  |> filter(fn: (r) => r[\"_field\"] == \"document_deleted\" or r[\"_field\"] == \"document_inserted\" or r[\"_field\"] == \"document_returned\" or r[\"_field\"] == \"document_updated\")\n  |> derivative(unit: v.windowPeriod, nonNegative: false)\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "Open connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mongodb\")\n  |> filter(fn: (r) => r[\"_field\"] == \"open_connections\")"
    }
   ]
  },
  {
   "title": "Flushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mongodb\")\n  |> filter(fn: (r) => r[\"_field\"] == \"flushes\")\n  |> derivative(unit: v.windowPeriod, nonNegative: true)\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  { "title": "Elasticsearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Node CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_load_average_1m\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"docker-cluster\")\n  |> group(columns: [\"node_host\",\"node_name\", \"node_id\", \"cluster_name\"], mode:\"by\")\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => exists r._value)"
    }
   ]
  },
  {
   "title": "Node Heap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "used =\n  from(bucket: \"telegraf\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_jvm\")\n    |> filter(fn: (r) => r[\"_field\"] == \"mem_heap_used_in_bytes\")\n    |> filter(fn: (r) => r[\"cluster_name\"] == \"docker-cluster\")\n    |> group(columns: [\"node_host\",\"node_name\", \"node_id\", \"cluster_name\"], mode:\"by\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)\n    |> filter(fn: (r) => exists r._value)\n    |> yield(name: \"used\")"
    }
   ]
  },
  {
   "title": "Node Swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "all = from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_os\")\n\ntotal = all\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_total_in_bytes\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"docker-cluster\")\n  |> group(columns: [\"node_host\",\"node_name\", \"node_id\", \"cluster_name\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> filter(fn: (r) => exists r._value)\n  |> yield(name: \"total\")\n\nused = all\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_used_in_bytes\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"docker-cluster\")\n  |> group(columns: [\"node_host\",\"node_name\", \"node_id\", \"cluster_name\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> filter(fn: (r) => exists r._value)\n  |> yield(name: \"used\")"
    }
   ]
  },
  {
   "title": "Node memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "all = from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_os\")\n\ntotal = all\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_total_in_bytes\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"docker-cluster\")\n  |> group(columns: [\"node_host\",\"node_name\", \"node_id\", \"cluster_name\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> filter(fn: (r) => exists r._value)\n  |> yield(name: \"total\")\n\nused = all\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_used_in_bytes\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"docker-cluster\")\n  |> group(columns: [\"node_host\",\"node_name\", \"node_id\", \"cluster_name\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> filter(fn: (r) => exists r._value)\n  |> yield(name: \"used\")"
    }
   ]
  },
  {
   "title": "Node Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "total =\n  from(bucket: \"telegraf\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_fs\")\n    |> filter(fn: (r) => r[\"_field\"] == \"total_total_in_bytes\")\n    |> filter(fn: (r) => r[\"cluster_name\"] == \"docker-cluster\")\n    |> group(columns: [\"node_host\",\"node_name\", \"node_id\", \"cluster_name\"], mode:\"by\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)\n    |> filter(fn: (r) => exists r._value)  \n    |> yield(name: \"total\")\n\navailable =\n  from(bucket: \"telegraf\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_fs\")\n    |> filter(fn: (r) => r[\"_field\"] == \"total_available_in_bytes\")\n    |> filter(fn: (r) => r[\"cluster_name\"] == \"docker-cluster\")\n    |> group(columns: [\"node_host\",\"node_name\", \"node_id\", \"cluster_name\"], mode:\"by\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)\n    |> filter(fn: (r) => exists r._value)\n    |> yield(name: \"available\")"
    }
   ]
  },
  {
   "title": "Node threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_jvm\")\n  |> filter(fn: (r) => r[\"_field\"] == \"threads_count\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"docker-cluster\")\n  |> group(columns: [\"node_host\",\"node_name\", \"node_id\", \"cluster_name\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"count\")\n\nfrom(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_jvm\")\n  |> filter(fn: (r) => r[\"_field\"] == \"threads_peak_count\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"docker-cluster\")\n  |> group(columns: [\"node_host\",\"node_name\", \"node_id\", \"cluster_name\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"peak_count\")"
    }
   ]
  },
  {
   "title": "${container}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "repeat": "container",
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\n  |> filter(fn: (r) => r[\"container_name\"] =~ /${container:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\n  |> filter(fn: (r) => r[\"container_name\"] =~ /${container:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_blkio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"io_service_bytes_recursive_read\" or r[\"_field\"] == \"io_service_bytes_recursive_write\")\n  |> filter(fn: (r) => r[\"container_name\"] =~ /${container:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_bytes\" or r[\"_field\"] == \"tx_bytes\")\n  |> filter(fn: (r) => r[\"container_name\"] =~ /${container:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    }
   ]
  }
 ]
}